# Secrets for the Laser Hair Removal Application
# Last updated: July 20, 2025, 06:43 PM CEST

database:
  encryption_key: "your-secure-32-byte-encryption-key-here"  # Replace with a 32-byte key for SQLCipher

notifications:
  smtp_username: "your-smtp-username"
  smtp_password: "your-smtp-password"
  sms_api_key: "your-sms-api-key"
  email_from: "no-reply@laserapp.com"
  sms_from: "LaserApp"

google:
  credentials_path: "config/credentials.json"  # Path to Google API client secrets file