# secrets.yaml - Configuration file for sensitive data
# This file contains sensitive credentials and must be excluded from version control (e.g., add to .gitignore).
# Update the following fields with your specific values before running the application.

# Database encryption settings
database:
  encryption_key: "your-32-byte-encryption-key-here"  # Required: 32-byte key for SQLCipher encryption (e.g., base64 encoded)

# SMTP email server settings for email_sender.py
notifications:
  smtp:
    host: "smtp.gmail.com"  # Required: SMTP server host (e.g., smtp.gmail.com for Gmail)
    port: 587  # Required: SMTP port (e.g., 587 for TLS)
    username: "your-email@example.com"  # Required: Email address for sending
    password: "your-app-specific-password"  # Required: App-specific password or token (not regular password for Gmail)

# Twilio settings for sms_sender.py
  twilio:
    account_sid: "your-twilio-account-sid"  # Required: Twilio Account SID
    auth_token: "your-twilio-auth-token"  # Required: Twilio Auth Token
    from_number: "+1234567890"  # Required: Twilio phone number for sending SMS

# Google/Apple Calendar API settings for calendar_sync.py
  calendar:
    google:
      client_id: "your-google-client-id.apps.googleusercontent.com"  # Required: Google OAuth Client ID
      client_secret: "your-google-client-secret"  # Required: Google OAuth Client Secret
      refresh_token: "your-google-refresh-token"  # Required: Google Refresh Token (obtained after OAuth flow)
    apple:
      client_id: "your-apple-client-id"  # Required: Apple Client ID (if using Apple Calendar)
      team_id: "your-apple-team-id"  # Required: Apple Team ID
      key_id: "your-apple-key-id"  # Required: Apple Key ID
      private_key: "your-apple-private-key"  # Required: Apple Private Key (in PEM format)

# Optional settings
logging:
  level: "INFO"  # Optional: Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL), defaults to INFO if omitted